name: Personoid
version: ${project.version}
main: us.notnotdoddy.personoid.Personoid
api-version: 1.18
authors: [ DefineDoddy, notnotnotswipez ]
description: An API designed to make creating, managing, and interacting with NPC's easy
website: www.personoid.com
commands:
  npc:
    permission: personoid.npc
    usage: /<command> [command]
    description: Accesses the NPC commands
    default: op
  profiler:
    permission: personoid.profiler
    usage: /<command> [display] [type]
    description: Accesses the profiler commands
    default: op
permissions:
  npc:
    description: Allows the user to access the NPC commands
  profiler:
    description: Allows the user to access the profiler commands