name: Personoid
version: '${project.version}'
main: com.personoid.PersonoidPlugin
authors: [ DefineDoddy, notnotnotswipez ]
description: A plugin that allows easy access to creating and modifying NPCs
api-version: 1.14
commands:
  personoid:
    description: Accesses Personoid's configurations
    usage: /personoid <sub-command>
    permission: personoid.*