name: Personoid
version: '${project.version}'
main: com.personoid.PersonoidPlugin
author: DefineDoddy
description: A plugin that allows easy access to creating and modifying NPCs
api-version: 1.17
commands:
  personoid:
    description: Accesses Personoid's configurations
    usage: /personoid <sub-command>
    permission: personoid.*