# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Setting up Java Development Kit"
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile Minecraft Spigot or Paper (BuildTools)
      uses: SpraxDev/Action-SpigotMC@v4.0.0
      with:
        remapped: true

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
